### PR TITLE
Remove deprecated Azure, Camera, and SoMA samples

### PR DESCRIPTION
**Pull request by pjcollins**
Removes all component references from mobile-samples, and updates the following README.md files to direct people to xamarin-forms-samples and/or the sample gallery.

* https://github.com/xamarin/mobile-samples/blob/remove-components/Azure/README.md
* https://github.com/xamarin/mobile-samples/blob/remove-components/Camera/README.md
* https://github.com/xamarin/mobile-samples/blob/remove-components/SoMA/README.md

### CODE REVIEW

**Comment by conceptdev** [comment]
@pjcollins were we able to validate everything builds after this change? As @bradumbaugh said, I think we probably just want to delete the SoMA sample, but the others are probably fine if everything works with the <component> elements removed?

**Comment by pjcollins** [comment]
@conceptdev I hadn't had a chance to test yet. I was hoping to be able to provide an update for all [Azure](https://github.com/xamarin/mobile-samples/tree/master/Azure) samples as well as part of this PR as those still all reference Components, but got pulled off on to a few other items. I will try to pick this up again today or tomorrow.

**Comment by conceptdev** [comment]
great! let's chat later in the week

**Comment by pjcollins** [comment]
I took a slightly more direct approach and cut out the now obsolete samples which reference Xamarin components. The `Azure`, `Camera`, and `SoMA` projects were stripped out, and their README.md files were updated to point folks to xamarin-forms-samples and/or the sample gallery:

https://github.com/xamarin/mobile-samples/blob/remove-components/Azure/README.md
https://github.com/xamarin/mobile-samples/blob/remove-components/Camera/README.md
https://github.com/xamarin/mobile-samples/tree/remove-components/SoMA

**Comment by conceptdev** [comment]
@pjcollins sadly, the Azure samples have [inbound links from Azure docs](https://github.com/xamarin/mobile-samples/tree/master/Azure), so we will need to put some effort into making them work rather than removing them.

Camera doesn't even appear in the Samples Gallery (probably due to lack of README file); so it's fine to remove Camera and SoMA.

**Comment by pjcollins** [comment]
@conceptdev thanks a bunch for the follow up on this, to keep history clean I'll just open a new PR with the Camera and SoMA removals.

**Pull request closed without merging**
