### PR TITLE
Removing OnPropertyChanged for angles (AnalogClock)

### PR DESCRIPTION
**Pull request by yosukesugishita**
We don’t need these because we already check DateTime for its property change.

### CODE REVIEW

**Comment by charlespetzold** [comment]
How does the Windows Phone version work with this change?

**Comment by yosukesugishita** [comment]
I've tested it with Android and iOS as I'm on a Mac.  Is there any way for me to test it with the Windows Phone with OS X?

**Comment by charlespetzold** [comment]
It doesn't need to be tested. It won't work on Windows Phone without the
calls to OnPropertyChanged.

**Comment by conceptdev** [comment]
We can only review and accept pull requests that have been tested and verified on all supported platforms. Thanks for your time.

(p.s. if you create PRs in future, please avoid modifying the `.gitignore` file which affects the entire repo)

**Pull request closed without merging**
