### PR TITLE
Added Netstandard sample

### PR DESCRIPTION
**Pull request by JonDouglas**

### CODE REVIEW

**Comment by conceptdev** [comment]
@JonDouglas so I just updated to **Xamarin Studio C9 stable** and back to this error (ps I re-installed [RC4 netcore](https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md) but didn't seem to help).

screen shot 2017-02-22 at 3 07 53 pm

screen shot 2017-02-22 at 3 05 23 pm

any ideas?

**Comment by JonDouglas** [comment]
@conceptdev I'll have to take a look at it when I get some free time. C9 is going to be pretty heavy.

**Comment by bradumbaugh** [comment]
@conceptdev @JonDouglas This builds/runs fine on VSMac 7.5.4. It's a bit of an old PR, though – would you still like to include this?

**Comment by JonDouglas** [comment]
@bradumbaugh I don't really see the purpose of this sample if we plan to migrate PCL -> Netstandard. I believe I added this back then to coincide the netstandard docs I wrote.

**Comment by bradumbaugh** [comment]
Sounds good, thanks @JonDouglas.

**Pull request closed without merging**
