### PR TITLE
Tasky updates

### PR DESCRIPTION
**Pull request by NathanCastle**
Added win phone 81 project to taskyportable

### CODE REVIEW

**Comment by paulraj24683** [comment]
i am not getting what is this.

**Comment by NathanCastle** [comment]
The tasky portable sample previously only had projects for windows phone 8, iOS and Android. I added a project for Windows Phone 8.1.

**Comment by paulraj24683** [comment]
ok. so i have to download all these?

**Comment by conceptdev** [comment]
@paulraj24683 it's likely that some time in the past you "watched" or "followed" these samples on Github, and you are receiving emails for pull requests and issues.

They don't happen often and so maybe this is unexpected for you - you can remove yourself from the list in Github.

**Pull request merged**
